#!/bin/bash

REGION="us-west-2"

if [ $# -eq 0 ]; then
    echo "Usage: $0 <keyfile.pem>"
    exit 1
fi

pemkey="$1" 
keyname=$(basename "$pemkey" .pem)
echo "Importing: $keyname"

# Extract public key from .pem and use it
ssh-keygen -y -f "$pemkey" | aws ec2 import-key-pair \
    --key-name "$keyname" \
    --public-key-material file:///dev/stdin \
    --region "$REGION"
    
echo "Imported key: $keyname"