#!/bin/bash

REGION="us-west-2"

if [ $# -eq 0 ]; then
    echo "Usage: $0 <keyfile.pub>"
    exit 1
fi

pubkey="$1" 
keyname=$(basename "$pubkey" .pub)
echo "Importing: $keyname"

aws ec2 import-key-pair \
    --key-name "$keyname" \
    --public-key-material "fileb://$pubkey" \
    --region "$REGION"
    
echo "Imported key: $keyname"